services:
  portfolio:
    build:
      context: .
      dockerfile: dockerfile
    container_name: henry-yusuf-portfolio
    restart: unless-stopped
    network_mode: bridge
    environment:
      - NODE_ENV=production
